#!/usr/bin/env bash
set -e

################################################################################
#  WHEN TO USE THIS SCRIPT
################################################################################
#
#  Use this on a machine WITHOUT INTERNET to run npm/build commands
#  while still using cached dependencies from .offline-cache/
#
#  Requires: .offline-cache/ folder (generated by prepare-offline.sh)
#
#  ⚠️  CRITICAL: Use on the SAME OS where you ran prepare-offline.sh
#  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  If you ran:  ./scripts/prepare-offline.sh --dist-linux
#  Then use:    ./scripts/use-offline-cache.sh  [on LINUX only]
#
#  If you ran:  ./scripts/prepare-offline.sh --dist-win
#  Then use:    ./scripts/use-offline-cache.sh  [on WINDOWS only]
#
#  If you ran:  ./scripts/prepare-offline.sh --dist-mac
#  Then use:    ./scripts/use-offline-cache.sh  [on MACOS only]
#
#  Reason: .offline-cache/ contains platform-specific binaries (Electron, etc.)
#
#  Example scenario:
#    1. You're on a laptop in the field (no WiFi, no internet)
#    2. You have the repo copied locally (with .offline-cache/ from a Linux prep)
#    3. You're running Linux on that laptop
#    4. Instead of: npm ci
#       Do this:    ./scripts/use-offline-cache.sh npm ci
#    5. Script sets env vars to use .offline-cache/ instead of internet
#    6. npm ci works! Downloads from local cache, not internet
#
#  Common commands to wrap:
#    ./scripts/use-offline-cache.sh npm ci              # Install deps
#    ./scripts/use-offline-cache.sh npm run dev         # Start dev mode
#    ./scripts/use-offline-cache.sh npm run build       # Build for prod
#    ./scripts/use-offline-cache.sh npm run dist:linux  # Package app
#
################################################################################

# Set environment variables to point to .offline-cache/ instead of internet
# This tells npm, Electron, and electron-builder where to look for cached files

export npm_config_cache="$PWD/.offline-cache/npm"
export ELECTRON_CACHE="$PWD/.offline-cache/electron"
export ELECTRON_BUILDER_CACHE="$PWD/.offline-cache/electron-builder"

# Run the command you passed in (e.g., npm ci, npm run dev, etc.)
exec "$@"
